apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-jogodavida
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-jogodavida
  template:
    metadata:
      labels:
        app: frontend-jogodavida
    spec:
      containers:
        - name: frontend
          image: frontend-jogodavida:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80  # altere se o container usar outra porta
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-jogodavida-service
spec:
  type: NodePort
  selector:
    app: frontend-jogodavida
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # porta externa (altere se necessário)
