apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogodavida-mpiomp
  labels:
    app: jogodavida
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jogodavida
  template:
    metadata:
      labels:
        app: jogodavida
    spec:
      containers:
        - name: jogodavida-container
          image: jogodavidampiomp:latest
          imagePullPolicy: Never  # usa a imagem local
          resources:
            limits:
              cpu: "4"
              memory: "1Gi"
            requests:
              cpu: "2"
              memory: "512Mi"
          tty: true
          stdin: true
      restartPolicy: Always
