apiVersion: v1
kind: ConfigMap
metadata:
  name: hostfile-config
data:
  hostfile: |
    omp_mpi_engine-0 slots=1
    omp_mpi_engine-1 slots=1
    omp_mpi_engine-2 slots=1
---
apiVersion: v1
kind: Service
metadata:
  name: omp_mpi_engine
spec:
  clusterIP: None
  selector:
    app: omp_mpi_engine
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: omp_mpi_engine
spec:
  serviceName: "omp_mpi_engine"
  replicas: 3
  selector:
    matchLabels:
      app: omp_mpi_engine
  template:
    metadata:
      labels:
        app: omp_mpi_engine
    spec:
      containers:
      - name: omp_mpi_engine
        image: jogodavidampiomp:latest
        command:
          - /bin/bash
          - -c
          - |
            if [[ "$(hostname)" == "omp_mpi_engine-0" ]]; then
              echo "Sou o master"
              mpirun --hostfile /config/hostfile -np 3 --allow-run-as-root ./out
            else
              echo "Sou um worker, aguardando..."
              sleep infinity
            fi
        volumeMounts:
          - name: hostfile-volume
            mountPath: /config
      volumes:
        - name: hostfile-volume
          configMap:
            name: hostfile-config
